### ISSUE TITLE
using AbstractLattices

### ISSUE THREAD

**Issue by chakravala** [scheinerman/HyperbolicPlane.jl#1]
Hi, I'm interested in using your package for plotting.

What's the purpose of `AbstractLattices` in this package? It does not seem to be used and is empty.

May I refer you to my package [Grassmann.jl](https://github.com/chakravala/Grassmann.jl) where I have defined `∧` operation, and I intend to define `∨` also. If you need this functionality, depending on your goals, perhaps Grassmann.jl would be useful?

**Comment by scheinerman** [comment]
Let me begin with a caveat: I'm not an expert programmer! The problem I had was that I use both \vee and \wedge operators in a few of my modules. For reasons I don't fully understand, if I do `using A` followed by `using B`, the `B`-version of these operators cause problems. The solution I was led to (with help from folks who know more than I do) is to create an "umbrella" module that defines those two operations and then extend from there. (I hope I'm using the right terms.)

So the answer to your question is that `AbstractLattices` just create "place holder functions" for \vee and \wedge, and then in my various modules that want to use those as functions (such as in my `HyperbolicPlane` module) I can `import` them and extend their definitions to the new types.

**Comment by chakravala** [comment]
Alright, now I understand! That makes sense, thank you for explaining. Well, the [Grassmann.jl](https://github.com/chakravala/Grassmann.jl) package can be used for [conformal geometric algebra](https://en.wikipedia.org/wiki/Conformal_geometric_algebra), so now I'm interested in `HyperbolicPlane` package also.

**Comment by chakravala** [comment]
Looks like maybe I should also use `AbstractLattices` in my packages `Grassmann` and `Dendriform`, since both of those packages also use those symbols.

**Comment by scheinerman** [comment]
I think that makes sense. Were you having issues if you used both during the same session?

**Comment by chakravala** [comment]
The issues I had were resolved after merging `HyperbolicPlane` just now, and now `Grassmann` and `Dendriform` both also import `AbstractLattices`, so that there is no currently forseeable issue.
